name: GPA Checker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0/20 0-15/1 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip3 install cryptography
          pip3 install beautifulsoup4
          pip3 install requests

      - name: Run Python script and get result
        id: run_script
        run: |
          STD_ID=${{ 24300180017 }} PASSWORD=${{ Lyh0060627 }} TOKEN=${{  f03346e27ce247a88c75f1351ff3431f }} python3 main.py > result.txt
          echo "RESULT=$(cat result.txt)" >> $GITHUB_ENV

      - name: Conditional update
        if: contains(env.RESULT, 'update')
        run: |
          git config --global user.email "suny21@m.fudan.edu.cn"
          git config --global user.name "Boreas618"
          git add *
          git commit -m "Automatic update of records"
          git push origin main
